# Generated by Django 2.1.2 on 2018-10-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_num', models.PositiveIntegerField(verbose_name='Period number')),
                ('year_start', models.SmallIntegerField()),
                ('year_end', models.SmallIntegerField(blank=True, null=True)),
                ('snap_end', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-period_num',),
            },
        ),
    ]
