# Generated by Django 2.1.2 on 2018-10-04 19:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('parliament', '0002_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=django.utils.timezone.now)),
                ('end', models.DateField(blank=True, null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Period')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='person.Person')),
            ],
        ),
        migrations.CreateModel(
            name='MemberChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('change_type', models.CharField(choices=[('mandatenotapplied', 'Mandát sa neuplatňuje'), ('active', 'Mandát vykonávaný (aktívny poslanec)'), ('substitutefolded', 'Mandát náhradníka zaniknutý'), ('substituteactive', 'Mandát náhradníka vykonávaný'), ('substitutegained', 'Mandát náhradníka získaný'), ('folded', 'Mandát zaniknutý'), ('gained', 'Mandát nadobudnutý vo voľbách')], max_length=64)),
                ('change_reason', models.TextField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Period')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='person.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Party')),
            ],
            options={
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='stood_for_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Party'),
        ),
    ]
