# Generated by Django 2.1.2 on 2018-10-08 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0003_auto_20181004_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True, null=True)),
                ('press_type', models.CharField(choices=[('other', 'Other type'), ('intag', 'International agreement'), ('petition', 'Petition'), ('information', 'Information'), ('draftlaw', 'Draft law'), ('report', 'Report')], db_index=True, max_length=24)),
                ('title', models.TextField()),
                ('press_num', models.CharField(db_index=True, max_length=24)),
                ('date', models.DateField(db_index=True)),
                ('url', models.URLField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presses', to='parliament.Period')),
            ],
            options={
                'verbose_name': 'press',
                'verbose_name_plural': 'presses',
            },
        ),
        migrations.CreateModel(
            name='PressAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='missing title', max_length=512)),
                ('url', models.URLField()),
                ('file', models.FilePathField(blank=True, null=True)),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='parliament.Press')),
            ],
        ),
    ]
