# Generated by Django 2.1.2 on 2018-10-08 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0005_session_sessionattachment_sessionprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(blank=True, db_index=True, max_length=24, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Club')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='parliament.Member')),
            ],
        ),
    ]
