# Generated by Django 2.1.2 on 2018-10-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('parliament', '0006_clubmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_num', models.PositiveIntegerField()),
                ('topic', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('result', models.CharField(choices=[('passed', 'Návrh prešiel'), ('did_not_pass', 'Návrh neprešiel'), ('parliament_unable', 'Parlament nebol uznášaniaschopný')], max_length=24)),
                ('press', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='parliament.Press')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='parliament.Session')),
            ],
            options={
                'ordering': ('-voting_num',),
            },
        ),
        migrations.CreateModel(
            name='VotingVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('Z', 'for'), ('P', 'against'), ('?', 'abstained'), ('N', 'did not vote'), ('0', 'absent')], max_length=4)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='person.Person')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='parliament.Voting')),
            ],
            options={
                'ordering': ('-voting__session__session_num', '-voting__voting_num'),
            },
        ),
    ]
