# Generated by Django 2.1.2 on 2018-10-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0007_voting_votingvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_id',
        ),
        migrations.AddField(
            model_name='session',
            name='external_id',
            field=models.PositiveIntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voting',
            name='external_id',
            field=models.PositiveIntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='external_id',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='press',
            name='external_id',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
