# Generated by Django 2.1.2 on 2018-10-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0008_auto_20181011_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Party'),
        ),
    ]
