# Generated by Django 2.1.2 on 2018-10-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0009_auto_20181011_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
