# Generated by Django 2.1.2 on 2018-10-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0010_auto_20181011_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
