# Generated by Django 2.1.2 on 2018-10-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_person_external_url'),
        ('parliament', '0011_member_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memberchange',
            unique_together={('person', 'period', 'date', 'change_type')},
        ),
    ]
