# Generated by Django 2.1.2 on 2018-10-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0012_auto_20181012_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='press',
            name='external_id',
        ),
    ]
