# Generated by Django 2.1.2 on 2018-10-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0013_remove_press_external_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='press',
            unique_together={('press_num', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionprogram',
            unique_together={('session', 'point')},
        ),
    ]
