# Generated by Django 2.1.2 on 2018-10-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0014_auto_20181015_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionprogram',
            name='state',
            field=models.CharField(choices=[('discussed', 'Prerokovaný bod programu'), ('notdiscussed', 'Neprerokovaný bod programu'), ('moved', 'Presunutý bod programu'), ('withdrawn', 'Stiahnutý bod programu'), ('interrupted', 'Prerušené rokovanie o bode programu')], max_length=24),
        ),
    ]
