# Generated by Django 2.1.2 on 2018-10-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0016_auto_20181016_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionprogram',
            name='text1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sessionprogram',
            name='text2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sessionprogram',
            name='text3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='sessionprogram',
            name='text',
        ),
        migrations.AlterUniqueTogether(
            name='sessionprogram',
            unique_together={('session', 'press', 'point', 'text1')},
        ),
    ]
