# Generated by Django 2.1.2 on 2018-10-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0017_auto_20181016_1752'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionprogram',
            unique_together=set(),
        )
    ]
