# Generated by Django 2.1.2 on 2018-10-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_person_external_url'),
        ('parliament', '0019_unique_indexes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('person', 'period')},
        ),
    ]
