# Generated by Django 2.1.2 on 2018-10-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0020_auto_20181017_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='membership',
            field=models.CharField(choices=[('chairman', 'Predsedníčka/predseda'), ('vice-chairman', 'Pod-predsedníčka/predseda'), ('member', 'Členka/člen')], db_index=True, default='', max_length=24),
            preserve_default=False,
        ),
    ]
