# Generated by Django 2.1.2 on 2018-10-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_person_external_url'),
        ('parliament', '0022_auto_20181017_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingvote',
            name='vote',
            field=models.CharField(choices=[('Z', 'Za'), ('P', 'Proti'), ('?', 'Zdržal(a) sa'), ('N', 'Nehlasoval(a)'), ('0', 'Neprítomná/ý')], max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='votingvote',
            unique_together={('voting', 'person')},
        ),
    ]
