# Generated by Django 2.1.2 on 2018-10-19 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0024_auto_20181019_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='end',
        ),
        migrations.RemoveField(
            model_name='member',
            name='start',
        ),
        migrations.AddField(
            model_name='memberactive',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active', to='parliament.Member'),
        ),
        migrations.AlterUniqueTogether(
            name='memberactive',
            unique_together={('member', 'start')},
        ),
    ]
