# Generated by Django 2.1.2 on 2018-10-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0028_auto_20181029_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='current_result',
            field=models.SmallIntegerField(choices=[(0, 'NR SR nebude pokračovať v rokovaní o návrhu zákona'), (1, 'NZ vzal navrhovateľ späť'), (2, 'Zápis uznesenia NR SR'), (3, 'NZ postúpil do redakcie'), (4, 'Zápis spoločnej správy výborov'), (5, 'NZ nebol schválený'), (6, 'Pripravená informácia k NZ'), (7, 'Zákon vyšiel v Zbierke zákonov'), (8, 'Zákon bol vrátený prezidentom'), (9, 'Zapísané uznesenie výboru'), (10, 'Výber právneho poradcu'), (11, 'NZ postúpil do II. čítania')]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='current_state',
            field=models.SmallIntegerField(choices=[(0, 'Evidencia'), (1, 'Uzavretá úloha'), (2, 'I. čítanie'), (3, 'II. čítanie'), (4, 'III. čítanie'), (5, 'Redakcia'), (6, 'Rokovanie výboru'), (7, 'Stanovisko k NZ'), (8, 'Rokovanie NR SR'), (9, 'Rokovanie gestorského výboru'), (10, 'Výber poradcov k NZ')]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='external_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='billprocessstep',
            name='external_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='billprocessstep',
            name='sent_standpoint',
            field=models.SmallIntegerField(choices=[(1, 'Súhlasný'), (0, 'Nesúhlasný')]),
        ),
        migrations.AlterField(
            model_name='billprocessstep',
            name='step_result',
            field=models.SmallIntegerField(choices=[(0, 'Zapísané rozhodnutie predsedu NR SR'), (1, 'Príprava informácie k NZ'), (2, 'NZ vzal navrhovateľ späť'), (3, 'NR SR nebude pokračovať v rokovaní o návrhu zákona'), (4, 'Zákon vyšiel v Zbierke zákonov.'), (5, 'NZ postupuje do redakcie'), (6, 'NZ postúpil do I. čítania'), (7, 'NZ postúpil do II. čítania'), (8, 'NZ postúpil do III. čítania'), (9, 'Zápis uznesenia / návrhu uznesenia výborov'), (10, 'NZ nebol schválený'), (11, 'Zákon bol vrátený prezidentom.')]),
        ),
        migrations.AlterField(
            model_name='billprocessstep',
            name='step_type',
            field=models.SmallIntegerField(choices=[(0, 'Podateľňa'), (1, 'Rozhodnutie predsedu NR SR'), (2, 'I. čítanie'), (3, 'II. čítanie'), (4, 'III. čítanie'), (5, 'Rokovanie gestorského výboru'), (6, 'Rokovanie výborov'), (7, 'Redakcia')]),
        ),
    ]
