# Generated by Django 2.1.2 on 2018-10-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0029_auto_20181030_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='current_result',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='current_state',
        ),
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'Novela zákona'), (1, 'Návrh nového zákona'), (2, 'Iný typ'), (3, 'Petícia'), (4, 'Medzinárodná zmluva'), (5, 'Správa'), (6, 'Ústavný zákon'), (7, 'Informácia'), (8, 'Návrh zákona o štátnom rozpočte'), (9, 'Zákon vrátený prezidentom')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='result',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'NR SR nebude pokračovať v rokovaní o návrhu zákona'), (1, 'NZ vzal navrhovateľ späť'), (2, 'Zápis uznesenia NR SR'), (3, 'NZ postúpil do redakcie'), (4, 'Zápis spoločnej správy výborov'), (5, 'NZ nebol schválený'), (6, 'Pripravená informácia k NZ'), (7, 'Zákon vyšiel v Zbierke zákonov'), (8, 'Zákon bol vrátený prezidentom'), (9, 'Zapísané uznesenie výboru'), (10, 'Výber právneho poradcu'), (11, 'NZ postúpil do II. čítania')], null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='state',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Evidencia'), (1, 'Uzavretá úloha'), (2, 'I. čítanie'), (3, 'II. čítanie'), (4, 'III. čítanie'), (5, 'Redakcia'), (6, 'Rokovanie výboru'), (7, 'Stanovisko k NZ'), (8, 'Rokovanie NR SR'), (9, 'Rokovanie gestorského výboru'), (10, 'Výber poradcov k NZ')], null=True),
        ),
    ]
