# Generated by Django 2.1.2 on 2018-10-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0030_auto_20181031_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberchange',
            name='change_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Mandát sa neuplatňuje'), (1, 'Mandát vykonávaný (aktívny poslanec)'), (2, 'Mandát náhradníka zaniknutý'), (3, 'Mandát náhradníka vykonávaný'), (4, 'Mandát náhradníka získaný'), (5, 'Mandát zaniknutý'), (6, 'Mandát nadobudnutý vo voľbách')]),
        ),
        migrations.AlterField(
            model_name='sessionprogram',
            name='point',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionprogram',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Prerokovaný bod programu'), (1, 'Neprerokovaný bod programu'), (2, 'Presunutý bod programu'), (3, 'Stiahnutý bod programu'), (4, 'Prerušené rokovanie o bode programu')]),
        ),
    ]
