# Generated by Django 2.1.2 on 2018-10-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0031_auto_20181031_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='result',
            field=models.SmallIntegerField(choices=[(0, 'Návrh prešiel'), (1, 'Návrh neprešiel'), (2, 'Parlament nebol uznášaniaschopný')]),
        ),
        migrations.AlterField(
            model_name='votingvote',
            name='vote',
            field=models.CharField(choices=[('Z', 'Za'), ('P', 'Proti'), ('?', 'Zdržal(a) sa'), ('N', 'Nehlasoval(a)'), ('0', 'Neprítomná/ý')], max_length=1),
        ),
    ]
