# Generated by Django 2.1.2 on 2018-11-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0033_auto_20181101_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='proposers',
            field=models.ManyToManyField(related_name='proposers', to='parliament.Member'),
        ),
        migrations.AlterField(
            model_name='press',
            name='press_type',
            field=models.SmallIntegerField(choices=[(0, 'Novela zákona'), (2, 'Iný typ'), (3, 'Petícia'), (4, 'Medzinárodná zmluva'), (5, 'Správa'), (6, 'Ústavný zákon'), (7, 'Informácia'), (8, 'Návrh zákona o štátnom rozpočte'), (9, 'Zákon vrátený prezidentom'), (1, 'Návrh zákona')], db_index=True),
        ),
    ]
