# Generated by Django 2.1.2 on 2018-11-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0034_auto_20181102_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillProposer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ('delivered',)},
        ),
        migrations.AlterField(
            model_name='bill',
            name='delivered',
            field=models.DateField(db_index=True),
        ),
        migrations.RemoveField(
            model_name='bill',
            name='proposers',
        ),
        migrations.AddField(
            model_name='bill',
            name='proposers',
            field=models.ManyToManyField(related_name='proposers', through='parliament.BillProposer', to='parliament.Member'),
        ),
        migrations.AddField(
            model_name='billproposer',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Bill'),
        ),
        migrations.AddField(
            model_name='billproposer',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Member'),
        ),
    ]
