# Generated by Django 2.1.2 on 2018-11-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0035_auto_20181102_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billprocessstep',
            name='step_type',
            field=models.SmallIntegerField(choices=[(0, 'Podateľňa'), (1, 'Rozhodnutie predsedu NR SR'), (2, 'I. čítanie'), (3, 'Rokovanie výborov'), (4, 'Rokovanie gestorského výboru'), (5, 'II. čítanie'), (6, 'III. čítanie'), (7, 'Redakcia')]),
        ),
    ]
