# Generated by Django 2.1.2 on 2018-11-07 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_person_external_url'),
        ('parliament', '0036_auto_20181104_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateAppearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True)),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField()),
                ('appearance_type', models.SmallIntegerField(choices=[(0, '-'), (1, 'Doplňujúca otázka / reakcia zadávajúceho'), (2, 'Prednesenie interpelácie'), (3, 'Prednesenie otázky'), (4, 'Uvádzajúci uvádza bod'), (5, 'Vstup predsedajúceho'), (6, 'Vystúpenie'), (7, 'Vystúpenie s faktickou poznámkou'), (8, 'Vystúpenie s procedurálnym návrhom'), (9, 'Vystúpenie spoločného spravodajcu'), (10, 'Vystúpenie v rozprave'), (11, 'Zodpovedanie otázky')])),
                ('video_url', models.URLField()),
                ('appearance_addition', models.CharField(blank=True, default='', max_length=128)),
                ('debater_ext', models.CharField(blank=True, default='', max_length=128)),
                ('debater_role', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
                ('debater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('press_num', models.ManyToManyField(blank=True, to='parliament.Press')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Session')),
            ],
            options={
                'ordering': ('external_id',),
            },
        ),
    ]
