# Generated by Django 2.1.2 on 2018-11-09 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0038_interpellation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True)),
                ('date', models.DateField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AmendmentSignedMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Amendment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Member')),
            ],
        ),
        migrations.CreateModel(
            name='AmendmentSubmitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Amendment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Member')),
            ],
        ),
        migrations.AlterField(
            model_name='interpellation',
            name='asked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.Member'),
        ),
        migrations.AddField(
            model_name='amendment',
            name='other_submitters',
            field=models.ManyToManyField(blank=True, related_name='other_submitters', through='parliament.AmendmentSubmitter', to='parliament.Member'),
        ),
        migrations.AddField(
            model_name='amendment',
            name='press',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Press'),
        ),
        migrations.AddField(
            model_name='amendment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Session'),
        ),
        migrations.AddField(
            model_name='amendment',
            name='signed_members',
            field=models.ManyToManyField(blank=True, related_name='signed_members', through='parliament.AmendmentSignedMember', to='parliament.Member'),
        ),
        migrations.AddField(
            model_name='amendment',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Member'),
        ),
        migrations.AddField(
            model_name='amendment',
            name='voting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.Voting'),
        ),
        migrations.AlterUniqueTogether(
            name='amendmentsubmitter',
            unique_together={('amendment', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='amendmentsignedmember',
            unique_together={('amendment', 'member')},
        ),
    ]
