# Generated by Django 2.1.2 on 2018-11-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0041_auto_20181109_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingvote',
            name='person',
        ),
    ]
