# Generated by Django 2.1.2 on 2018-11-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0043_auto_20181109_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendment',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
