# Generated by Django 2.1.2 on 2018-11-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0045_auto_20181111_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='coalition',
            field=models.BooleanField(default=False),
        ),
    ]
