# Generated by Django 2.1.2 on 2018-11-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0046_club_coalition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
