# Generated by Django 2.1.3 on 2018-11-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0048_auto_20181112_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amendment',
            name='title',
        ),
    ]
