# Generated by Django 2.1.3 on 2018-11-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0049_remove_amendment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendment',
            name='signed_members',
            field=models.ManyToManyField(blank=True, related_name='signed_amendments', through='parliament.AmendmentSignedMember', to='parliament.Member'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='submitters',
            field=models.ManyToManyField(blank=True, related_name='submitted_amendments', through='parliament.AmendmentSubmitter', to='parliament.Member'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='proposers',
            field=models.ManyToManyField(related_name='bills', through='parliament.BillProposer', to='parliament.Member'),
        ),
        migrations.AlterField(
            model_name='debateappearance',
            name='debater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debate_appearances', to='parliament.Member'),
        ),
        migrations.AlterField(
            model_name='interpellation',
            name='asked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interpellations', to='parliament.Member'),
        ),
    ]
