# Generated by Django 2.1.3 on 2018-12-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0050_auto_20181121_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmember',
            options={'ordering': ('-start',)},
        ),
        migrations.AlterField(
            model_name='votingvote',
            name='vote',
            field=models.SmallIntegerField(choices=[(0, 'Za'), (1, 'Proti'), (2, 'Zdržal(a) sa'), (3, 'Nehlasoval(a)'), (4, 'Neprítomná/ý')]),
        ),
    ]
