# Generated by Django 2.1.3 on 2019-01-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0051_auto_20181204_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='proposer_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Poslanci NR SR'), (1, 'Vláda'), (2, 'Výbor')], null=True),
        ),
    ]
