# Generated by Django 2.1.7 on 2019-03-10 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0054_auto_20190302_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('external_id', models.IntegerField(unique=True)),
                ('url', models.URLField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Period')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.SmallIntegerField(choices=[(0, 'predsedníčka'), (1, 'predseda'), (2, 'podpredsedníčka'), (3, 'podpredseda'), (4, 'členka'), (5, 'člen'), (6, 'náhradná členka'), (7, 'náhradný člen'), (8, 'overovateľka'), (9, 'overovateľ')])),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='parliament.Committee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to='parliament.Member')),
            ],
        ),
    ]
