# Generated by Django 2.1.7 on 2019-03-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0055_committee_committeemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
