# Generated by Django 2.1.7 on 2019-03-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0056_committee_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('place', models.TextField()),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Committee')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeSessionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('topic', models.CharField(max_length=2048)),
                ('press', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.Press')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.CommitteeSession')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='committeesessionpoint',
            unique_together={('session', 'topic')},
        ),
        migrations.AlterUniqueTogether(
            name='committeesession',
            unique_together={('committee', 'start')},
        ),
    ]
