# Generated by Django 2.1.7 on 2019-04-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0057_auto_20190330_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeesessionpoint',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='parliament.CommitteeSession'),
        ),
    ]
