# Generated by Django 2.2.5 on 2020-04-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0058_auto_20190415_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='committee',
            unique_together={('period', 'name')},
        ),
    ]
