# Generated by Django 2.1.2 on 2018-10-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64)),
                ('forename', models.CharField(db_index=True, max_length=128)),
                ('surname', models.CharField(db_index=True, max_length=128)),
                ('born', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(choices=[('unknown', 'Unknown'), ('slovak', 'Slovak'), ('hungarian', 'Hungarian'), ('romani', 'Romani'), ('rusyn', 'Rusyn'), ('russian', 'Russian'), ('czech', 'Czech'), ('ukrainian', 'Ukrainian')], db_index=True, default='unknown', max_length=24)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='member_images/')),
                ('external_photo_url', models.URLField(blank=True, null=True)),
                ('external_id', models.PositiveIntegerField(db_index=True)),
                ('external_url', models.URLField()),
                ('residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Village')),
            ],
        ),
    ]
