# Generated by Django 2.1.2 on 2018-10-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20181011_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='external_url',
        ),
    ]
