# Generated by Django 2.1.2 on 2018-11-15 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parliament', '0048_auto_20181112_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_count', models.PositiveSmallIntegerField()),
                ('amendment_coalition', models.PositiveSmallIntegerField()),
                ('amendment_opposition', models.PositiveSmallIntegerField()),
                ('amendment_government', models.PositiveSmallIntegerField()),
                ('amendment_committee', models.PositiveSmallIntegerField()),
                ('debate_count_coalition', models.PositiveSmallIntegerField()),
                ('debate_count_opposition', models.PositiveSmallIntegerField()),
                ('debate_count_government', models.PositiveSmallIntegerField()),
                ('debate_count_committee', models.PositiveSmallIntegerField()),
                ('debate_member_count', models.PositiveSmallIntegerField()),
                ('debate_seconds_coalition', models.PositiveSmallIntegerField()),
                ('debate_seconds_opposition', models.PositiveSmallIntegerField()),
                ('debate_seconds_government', models.PositiveSmallIntegerField()),
                ('debate_seconds_committee', models.PositiveSmallIntegerField()),
                ('interpellation_count', models.PositiveSmallIntegerField()),
                ('voting_coalition_for', models.PositiveSmallIntegerField()),
                ('voting_coalition_against', models.PositiveSmallIntegerField()),
                ('voting_coalition_abstain', models.PositiveSmallIntegerField()),
                ('voting_coalition_dnv', models.PositiveSmallIntegerField()),
                ('voting_coalition_absent', models.PositiveSmallIntegerField()),
                ('voting_opposition_for', models.PositiveSmallIntegerField()),
                ('voting_opposition_against', models.PositiveSmallIntegerField()),
                ('voting_opposition_abstain', models.PositiveSmallIntegerField()),
                ('voting_opposition_dnv', models.PositiveSmallIntegerField()),
                ('voting_opposition_absent', models.PositiveSmallIntegerField()),
                ('voting_government_for', models.PositiveSmallIntegerField()),
                ('voting_government_against', models.PositiveSmallIntegerField()),
                ('voting_government_abstain', models.PositiveSmallIntegerField()),
                ('voting_government_dnv', models.PositiveSmallIntegerField()),
                ('voting_government_absent', models.PositiveSmallIntegerField()),
                ('voting_committee_for', models.PositiveSmallIntegerField()),
                ('voting_committee_against', models.PositiveSmallIntegerField()),
                ('voting_committee_abstain', models.PositiveSmallIntegerField()),
                ('voting_committee_dnv', models.PositiveSmallIntegerField()),
                ('voting_committee_absent', models.PositiveSmallIntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Club')),
            ],
            options={
                'verbose_name': 'Club Stats',
                'verbose_name_plural': 'Club Stats',
            },
        ),
        migrations.AlterUniqueTogether(
            name='clubstats',
            unique_together={('club', 'date')},
        ),
    ]
