# Generated by Django 2.1.3 on 2018-11-19 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0049_remove_amendment_title'),
        ('parliament_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_count', models.PositiveSmallIntegerField()),
                ('amendment_count', models.PositiveSmallIntegerField()),
                ('interpellation_count', models.PositiveSmallIntegerField()),
                ('debate_count', models.PositiveSmallIntegerField()),
                ('debate_seconds', models.PositiveSmallIntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_stats', to='parliament.Member')),
            ],
            options={
                'verbose_name': 'MP Stats',
                'verbose_name_plural': 'MP Stats',
            },
        ),
        migrations.AlterUniqueTogether(
            name='memberstats',
            unique_together={('member', 'date')},
        ),
    ]
