# Generated by Django 2.1.3 on 2018-11-28 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0050_auto_20181121_1046'),
        ('parliament_stats', '0002_auto_20181119_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('bill_count_by_coalition', models.PositiveSmallIntegerField()),
                ('bill_count_by_opposition', models.PositiveSmallIntegerField()),
                ('amendment_count_by_coalition', models.PositiveSmallIntegerField()),
                ('amendment_count_by_opposition', models.PositiveSmallIntegerField()),
                ('interpellation_count_by_coalition', models.PositiveSmallIntegerField()),
                ('interpellation_count_by_opposition', models.PositiveSmallIntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_stats', to='parliament.Period')),
            ],
            options={
                'verbose_name': 'Global Stats',
                'verbose_name_plural': 'Global Stats',
            },
        ),
        migrations.AlterUniqueTogether(
            name='globalstats',
            unique_together={('period', 'date')},
        ),
    ]
